### PR TITLE
Use full page width.

### PR DESCRIPTION
**Pull request by potthast**
The overview table will use the full page width instead of being artificially forced into a middle column view.
Tried to make minimal changes; please double-check.

### CODE REVIEW

**Comment by najtin** [comment]
Did you change the layout of all the other pages too?

**Comment by potthast** [comment]
Yes; see all the individual commits, which are not the same file, but different ones in different hugo sub folder.

**Comment by najtin** [comment]
Yes, i saw that and i was wondering, if it is the result of a side effect or an intended change. Looks fine, to me. But i'll also try it locally on my machine. If all files contain the proper change notice to satisfy the apache2.0 license, then i'll merge and deploy.

**Comment by potthast** [comment]
Ah, I see: please add that if needed.

**Pull request merged**
